### ISSUE TITLE
Should we be relying on the output of llvm-readelf as our test oracle? 

### ISSUE THREAD

**Issue by jacob-hughes** [softdevteam/ykstackmaps#3]
LLVM does not seem to support parsing version 3 stackmap sections. When compiled without debug flags (which cause an assertion fail when trying to read any stackmap != version 2), LLVM will silently attempt to create a `StackmapV2Parser` and interpret the stackmap section according to that spec. This makes me nervous about using `llvm-readelf` as a source of truth given that `ykstackmaps` only offers support for version 3 stackmaps.

I think that we should aim to move away from this for checking our expected case in testing. Unfortunately I don't have a good alternative suggestion, other than to perhaps use some test cases from the llvm statepoint intrinsic. This has concrete documentation in how it makes use of the v3 stackmap (https://llvm.org/docs/Statepoints.html#stack-map-format).

This way, we could setup a couple of ELF files with statepoint info in their stackmap sections and assert that we get the numbers we want out of the `ykstackmap` parser instead of comparing data from `llvm-readelf`'s parser.

Happy to discuss if you have alternate suggestions, but if you think this is the way forward I can make a PR for this.

**Comment by ltratt** [comment]
One obvious question is: how different are v2 and v3 stackmap formats? Would it be easier to change `llvm-readelf` (if, say, all we have to do is copy the v2 parser and make some tweaks)?

**Comment by jacob-hughes** [comment]
It took a long time to actually find the spec for the version 2 stackmap. But it seems not a lot has changed. 
```diff
diff --git a/smv2 b/smv3
index 0a0ab2e..3095dbe 100644
--- a/smv2
+++ b/smv3
@@ -1,5 +1,5 @@
 Header {
-  uint8  : Stack Map Version (current version is 2)
+  uint8  : Stack Map Version (current version is 3)
   uint8  : Reserved (expected to be 0)
   uint16 : Reserved (expected to be 0)
 }
@@ -21,10 +21,13 @@ StkMapRecord[NumRecords] {
   uint16 : NumLocations
   Location[NumLocations] {
     uint8  : Register | Direct | Indirect | Constant | ConstantIndex
-    uint8  : Reserved (location flags)
+    uint8  : Reserved (expected to be 0)
+    uint16 : Location Size
     uint16 : Dwarf RegNum
+    uint16 : Reserved (expected to be 0)
     int32  : Offset or SmallConstant
   }
+  uint32 : Padding (only if required to align to 8 byte)
   uint16 : Padding
   uint16 : NumLiveOuts
   LiveOuts[NumLiveOuts]
```

[Stackmap V2 spec](http://releases.llvm.org/4.0.1/docs/StackMaps.html#stack-map-format)
[Stackmap V3 spec](https://llvm.org/docs/StackMaps.html#stack-map-format)

I now have a local fix of the `llvm-readelf` stackmap parser, it's only a few lines. It might be worth submitting a PR for that to LLVM and using that instead. Regardless, it will take a while to make it upstream. If we decide to use this instead, how would we manage this as part of ykstackmaps? Check the modified `llvm-readelf` bin into the repo?

**Comment by vext01** [comment]
Yes, this is unfortunate. Of course at the time of implementing ykstackmaps, I didn't appreciate the v2 vs. v3 problems in LLVM.

I agree that fixing llvm-readelf seems the best way forward (and making it crash if the version isn't one that can be decoded.

Will you make llvm-readelf read both v2 and v3 stackmaps? Or just update the parser to version 3?

**Comment by jacob-hughes** [comment]
> Will you make llvm-readelf read both v2 and v3 stackmaps?

Probably not to be honest, it seems in the past there was no effort to maintain backwards compatibility when transitioning from v1 to v2. It simplifies the implementation too.

**Comment by vext01** [comment]
Fair enough.
